version: 2

sources:
  - name: raw_data
    schema: gz_raw_data
    description: Raw data productos, ventas y shipments
    tables:
      - name: product
        identifier: raw_gz_product
        description: Raw data productos
      - name: sales
        identifier: raw_gz_sales
        description: Raw data ventas
      - name: ship
        identifier: raw_gz_ship
        description: Raw data shipments

#Adding campaings
      - name: adwords
        identifier: raw_gz_adwords
        description: Adwords campaing data
      - name: bing
        identifier: raw_gz_bing
        description: Bing campaing data
      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo campaing data
      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook campaing data